### ISSUE TITLE
Eliminar los botones 1,2,3,4,5 en 

### ISSUE THREAD

**Issue by cmd-AJ** [cmd-AJ/Ing-Software#6]
La página de About tiene unos botones que son 1,2,3,4,5 yse redirigen hacia arriba o reedireccionan a la pagina nuevamente por favor eliminarlo.
![image](https://github.com/user-attachments/assets/d25f5aea-a101-461e-aaac-f6c0fc82e004)

**Comment by josuemj** [comment]
Numbers list removed
![image](https://github.com/user-attachments/assets/f53d97c7-fb9c-46a8-9b1b-0db37d92ec4a)
