### ISSUE TITLE
Añadanle CI/CD a su proyecto

### ISSUE THREAD

**Issue by ElrohirGT** [cmd-AJ/Ing-Software#8]
**se tenía que decir y se dijo.jpg**

**Comment by cmd-AJ** [comment]
Buenas tardes @ElrohirGT nuestro equipo no puede realizar el CI/CD debido a que nuestro estado de tiempo es inalcanzable para implementarlo.

**Comment by ElrohirGT** [comment]
![image](https://github.com/user-attachments/assets/43280486-07d8-4d62-8a17-ac9e3ab68c2e)
